export const  ONLOAD_REQUEST = 'ONLOAD_REQUEST',
	ONLOAD_SUCCESS = 'ONLOAD_SUCCESS',
	ONLOAD_ERROR = 'ONLOAD_ERROR';

export const  TEMP_BUTTON_TOGGLE_START = 'TEMP_BUTTON_TOGGLE_START',
	TEMP_BUTTON_TOGGLE_SUCCESS = 'TEMP_BUTTON_TOGGLE_SUCCESS',
	TEMP_BUTTON_TOGGLE_ERROR = 'TEMP_BUTTON_TOGGLE_ERROR';

export const  INPUT_QUERY = 'INPUT_QUERY';