export const  WEATHER_REQUEST = 'WEATHER_REQUEST',
	WEATHER_REQUEST_SUCCESS = 'WEATHER_REQUEST_SUCCESS',
	WEATHER_REQUEST_ERROR = 'WEATHER_REQUEST_ERROR';

export const  TEMP_BUTTON_TOGGLE_START = 'TEMP_BUTTON_TOGGLE_START',
	TEMP_BUTTON_TOGGLE_SUCCESS = 'TEMP_BUTTON_TOGGLE_SUCCESS',
	TEMP_BUTTON_TOGGLE_ERROR = 'TEMP_BUTTON_TOGGLE_ERROR';

export const  INPUT_QUERY = 'INPUT_QUERY';